source=~/.config/mango/modules/appearance.conf
source=~/.config/mango/modules/autostart.conf
source=~/.config/mango/modules/binds.conf
source=~/.config/mango/modules/input.conf
source=~/.config/mango/modules/layout.conf
source=~/.config/mango/modules/monitors.conf
source=~/.config/mango/modules/rules.conf
