set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

set -g base-index 1
set -g renumber-windows on
set -g allow-passthrough on
set -s set-clipboard on

setw -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi V send-keys -X select-line
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind c new-window -a -c "#{pane_current_path}"
bind C new-window -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

set -g pane-border-lines single
set -g pane-border-style default
set -g pane-active-border-style default

set -g status-position top
set -g status-justify centre
set -g status-style default
set -g status-bg default

set -g status-left '#([ $(tmux show-option -qv key-table) = "off" ] && echo " [OFF] ")'
set -g status-left-length 20
set -g status-right ''

setw -g window-status-separator ''
setw -g window-status-format '  #I #W #F  '
setw -g window-status-current-format '  #I #W #F  '
setw -g window-status-current-style default
setw -g window-status-style default

bind -T root F12 \
  set prefix None \;\
  set key-table off \;\
  set status-style default \;\
  if -F '#{pane_in_mode}' 'send-keys -X cancel' \;\
  refresh-client -S

bind -T off F12 \
  set -u prefix \;\
  set -u key-table \;\
  set -u status-style \;\
  refresh-client -S
