[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c-sharp"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["omnisharp"]

[[language]]
name = "cpp"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "dockerfile"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "go"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "html"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "javascript"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "json"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "jsx"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "lua"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "markdown"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "meson"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["mesonlsp"]

[[language]]
name = "nix"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["nixd"]

[[language]]
name = "php"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["phpactor"]

[[language]]
name = "python"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["pylsp"]

[[language]]
name = "qml"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["qmlls"]

[[language]]
name = "rust"
auto-format = true
indent = { tab-width = 4, unit = "    " }
language-servers = ["rust-analyzer"]

[[language]]
name = "toml"
auto-format = true
indent = { tab-width = 2, unit = "  " }
language-servers = ["taplo"]

[[language]]
name = "tsx"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "typescript"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "xml"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "yaml"
auto-format = true
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "zig"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[language-server.mesonlsp]
command = "mesonlsp"

[language-server.nixd]
command = "nixd"

[language-server.omnisharp]
command = "OmniSharp"

[language-server.phpactor]
command = "phpactor"

[language-server.pylsp]
command = "pylsp"

[language-server.qmlls]
command = "qmlls"

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.taplo]
command = "taplo"
