blur=0
shadows=0
animations=0

border_radius=0
no_radius_when_single=0

focused_opacity=1.0
unfocused_opacity=0.95

focuscolor=0xf4b8e4ff
bordercolor=0x00000000

maximizescreencolor=0xf4b8e4ff
scratchpadcolor=0xf4b8e4ff
urgentcolor=0xf4b8e4ff
globalcolor=0xf4b8e4ff
overlaycolor=0xf4b8e4ff

rootcolor=0x323232ff

gappih=3
gappiv=3
gappoh=3
gappov=3

borderpx=3
