exec-once=noctalia-shell
exec-once=swayidle -w timeout 300 'noctalia-shell ipc call lockScreen lock' timeout 600 'mmsg dispatch disable_monitor,eDP-1' resume 'mmsg dispatch enable_monitor,eDP-1' before-sleep 'noctalia-shell ipc call lockScreen lock'
exec-once=wl-paste --type text --watch cliphist store
exec-once=wl-paste --type image --watch cliphist store
exec-once=~/.config/mango/scripts/autostart.sh
