bind=SUPER+SHIFT,r,spawn,~/.config/mango/scripts/reload-config.sh

bind=SUPER,Return,spawn,kitty
bind=SUPER,Q,killclient,
bind=SUPER+SHIFT,Q,quit,

bind=SUPER,B,spawn,firefox-devedition
bind=SUPER,P,spawn,rofi-pass

bind=SUPER,space,spawn,rofi -show drun
bind=SUPER+CTRL,space,spawn_shell,cliphist list | rofi -dmenu | cliphist decode | wl-copy
bind=SUPER+ALT,space,spawn,rofimoji --selector rofi --action copy

bind=SUPER+ALT,L,spawn,~/.config/mango/scripts/layout-change.sh

bind=SUPER+SHIFT,Escape,spawn,noctalia-shell ipc call lockScreen lock

bind=SUPER,F,togglemaximizescreen,
bind=SUPER+SHIFT,F,togglefullscreen,

bindr=NONE,Print,spawn_shell,grim -t ppm -g "$(slurp)" - | satty --filename - --fullscreen --copy-command wl-copy --output-filename ~/Pictures/screenshots/$(date +%Y-%m-%d_%H-%M-%S).png

bindr=SHIFT,Print,spawn,~/.config/mango/scripts/screen-record.sh

bind=SUPER+SHIFT,space,togglefloating,

bind=SUPER,H,focusdir,left
bind=SUPER,J,focusdir,down
bind=SUPER,K,focusdir,up
bind=SUPER,L,focusdir,right

bind=SUPER+SHIFT,H,exchange_client,left
bind=SUPER+SHIFT,J,exchange_client,down
bind=SUPER+SHIFT,K,exchange_client,up
bind=SUPER+SHIFT,L,exchange_client,right

bind=SUPER+CTRL,H,resizewin,-40,0
bind=SUPER+CTRL,L,resizewin,40,0
bind=SUPER+CTRL,K,resizewin,0,-40
bind=SUPER+CTRL,J,resizewin,0,40

bind=SUPER,1,view,1
bind=SUPER,2,view,2
bind=SUPER,3,view,3
bind=SUPER,4,view,4
bind=SUPER,5,view,5
bind=SUPER,6,view,6
bind=SUPER,7,view,7
bind=SUPER,8,view,8
bind=SUPER,9,view,9

bind=SUPER+SHIFT,1,tag,1
bind=SUPER+SHIFT,2,tag,2
bind=SUPER+SHIFT,3,tag,3
bind=SUPER+SHIFT,4,tag,4
bind=SUPER+SHIFT,5,tag,5
bind=SUPER+SHIFT,6,tag,6
bind=SUPER+SHIFT,7,tag,7
bind=SUPER+SHIFT,8,tag,8
bind=SUPER+SHIFT,9,tag,9

bind=SUPER,S,toggle_scratchpad,
bind=SUPER+SHIFT,S,minimized,

mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%+
bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_SINK@ 5%-
bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_SINK@ toggle
bind=NONE,XF86AudioMicMute,spawn,wpctl set-mute @DEFAULT_SOURCE@ toggle

bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl -e4 -n2 set 5%+
bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl -e4 -n2 set 5%-
