scroller_structs=20
scroller_default_proportion=0.5
scroller_focus_center=0
scroller_prefer_center=0
scroller_prefer_overspread=0
scroller_ignore_proportion_single=1

new_is_master=1
default_mfact=0.5
default_nmaster=1

smartgaps=0
no_border_when_single=0

focus_on_activate=1
idleinhibit_ignore_visible=0

sloppyfocus=1
warpcursor=1

focus_cross_monitor=0
focus_cross_tag=0

enable_floating_snap=0
snap_distance=30

drag_tile_to_tile=1

scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
