tagrule=id:1,layout_name:dwindle
tagrule=id:2,layout_name:dwindle
tagrule=id:3,layout_name:dwindle
tagrule=id:4,layout_name:dwindle
tagrule=id:5,layout_name:dwindle
tagrule=id:6,layout_name:dwindle
tagrule=id:7,layout_name:dwindle
tagrule=id:8,layout_name:dwindle
tagrule=id:9,layout_name:dwindle

windowrule=tags:2,appid:firefox-devedition
windowrule=tags:3,appid:jetbrains-idea
windowrule=tags:4,appid:Postman
windowrule=tags:5,appid:code
windowrule=tags:8,appid:vesktop
windowrule=tags:9,appid:Spotify
