gui:
    border: rounded
    theme:
        activeBorderColor:
            - "#cba6f7"
            - bold
        inactiveBorderColor:
            - "#585b70"
        searchingActiveBorderColor:
            - "#f9e2af"
        optionsTextColor:
            - "#cdd6f4"
        selectedLineBgColor:
            - "#313244"
        cherryPickedCommitBgColor:
            - "#45475a"
        cherryPickedCommitFgColor:
            - "#cba6f7"
        unstagedChangesColor:
            - "#f38ba8"
        defaultFgColor:
            - "#cdd6f4"
