name: Build NixOS Flake
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NIX_CONFIG: experimental-features = nix-command flakes
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix flake check

  update:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    env:
      NIX_CONFIG: experimental-features = nix-command flakes
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - run: nix flake update
      - uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update flake inputs"
          title: "chore: update flake inputs"
          branch: update-flake-inputs
          delete-branch: true
