name: Weekly system update

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      NIX_CONFIG: experimental-features = nix-command flakes

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - run: nix flake update

      - uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore(nixos): weekly system update"
          title: "chore(nixos): weekly system update"
          branch: weekly-system-update
          delete-branch: true
          labels: dependencies
